version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn
      - run:
          name: Build Production API
          command: yarn run build
      - persist_to_workspace:
          root: dist
          paths:
            - index.js
  deploy:
    docker:
      - image: circleci/buildpack-deps:zesty
    steps:
      - attach_workspace:
          at: dist
      - add_ssh_keys:
          fingerprints:
            - "b3:d7:69:6a:00:79:ba:61:37:fa:b7:80:38:6c:c6:14"
      - run:
          name: Add Host to Known Hosts
          command: ssh-keyscan -H prestonmontewest.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy Bundle
          command: scp dist/index.js ubuntu@prestonmontewest.com:/var/www/prestonmontewest/api
      - run:
          name: Restart API Service
          command: ssh ubuntu@prestonmontewest.com 'sudo systemctl restart prestonmontewest-api'
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
